### ISSUE TITLE
APPAnalyzeCore/IPAParser.swift:141: Fatal error

### ISSUE THREAD

**Issue by yangbo930204** [helele90/APPAnalyze#2]
感谢提供工具，我在使用中遇见以下问题：assetutil环境地址：/usr/bin/assetutil
APPAnalyzeCore/IPAParser.swift:141: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=260 "The folder “Frameworks” doesn’t exist." UserInfo={NSFilePath=--output/Frameworks, NSUserStringVariant=(
    Folder
), NSUnderlyingError=0x6000028082a0 {Error Domain=NSOSStatusErrorDomain Code=-43 "fnfErr: File not found"}}

**Comment by helele90** [comment]
你看看传的.app 是不是不正确， ipa需要先解压出来

**Comment by yangbo930204** [comment]
> 

啊是，解出来的地址不对，没注意，耽误你宝贵的时间了，感谢感谢，工具很好用～
