### ISSUE TITLE
源码下载下来 提示APPAnalyzeCore 缺少swiftjson依赖

### ISSUE THREAD

**Issue by luckyczh** [helele90/APPAnalyze#4]
源码下载下来 提示APPAnalyzeCore 缺少swiftjson依赖。
命令行方式下载下来 不是可执行文件

**Comment by helele90** [comment]
这个主要是XCode 的 Swift Package Manager 没有下载下来 swiftjson 导致的。你重试几次试试

**Comment by helele90** [comment]
@luckyczh

**Comment by luckyczh** [comment]
> @luckyczh

package dependencies 里只有 swift-argument-parser 没有swiftjson。而且报错的是APPAnalyzeCore，这个是你们的framework啊。

**Comment by luckyczh** [comment]
<img width="1090" alt="image" src="https://github.com/helele90/APPAnalyze/assets/24567517/c850a488-ea73-40c5-a811-d1a8ffc7762a">

**Comment by luckyczh** [comment]
<img width="1403" alt="image" src="https://github.com/helele90/APPAnalyze/assets/24567517/a292a9bd-22a9-4a5d-80ff-34600b581021">

**Comment by helele90** [comment]
@luckyczh 可能我的 Demo 忘记加上这个了。我补一下。。你先加一个 swifyJSON 试试
