### ISSUE TITLE
下载下来后，在文件目录执行指令执行不了

### ISSUE THREAD

**Issue by RongLi77** [helele90/APPAnalyze#5]
command not found: APPAnalyzeCommand

**Comment by helele90** [comment]
用完整的路径试试 /Users/test/APPAnalyzeCommand

**Comment by jonasZhangAnker** [comment]
> command not found: APPAnalyzeCommand
I tried using: sudo mv /path/to/downloaded/APPAnalyzeCommand /usr/local/bin/ and executed sudo chmod +x /usr/local/bin/APPAnalyzeCommand and successfully ran APPAnalyzeCommand --help
