### ISSUE TITLE
执行脚本，显示路径错误

### ISSUE THREAD

**Issue by goooooooooodYao** [helele90/APPAnalyze#6]
您好，我执行/Users/yizhikeji_yao/Desktop/APPAnalyzeCommand --ipa /Users/yizhikeji_yao/Desktop/UKUOfferDev/UKUOfferDev.app --output /Users/yizhikeji_yao/Desktop/output 的时候，一直报错误：
Command.swift-38:错误输出:-["-arch", "arm64", "/Users/yizhikeji_yao/Desktop/UKUOfferDev/UKUOfferDev.app/UKUOfferDev"]-error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/size: can't open file: /Users/yizhikeji_yao/Desktop/UKUOfferDev/UKUOfferDev.app/UKUOfferDev (Not a directory)

**Comment by helele90** [comment]
按理说UKUOfferDev.app 这个名字，里面应该会有一个UKUOfferDev的 macho 才对。是不是改过文件名字啊

**Comment by goooooooooodYao** [comment]
确实是
